### PR TITLE
yamitranscode: make vp9 encoder work with yamitranscode

### LINKED ISSUE #31: yamitranscode: vp9 encoder doesn't work with yamitranscode
Especially when using ivf as the output extension yamitranscode can not operate properly.

### PR DESCRIPTION
**Pull request by chivakker**
yamitranscode is not honoring the codec name on the command line
so it is not possible to know which codec is intended for the output
if a common extension is given. So far, common extension is ivf and it
is required that yamitranscode calls EncodeOutput->create with a codec name
for examples to run properly

supported examples below, the output file is modified on this patch. The
rest of the command line options can be modified at will

yamitranscode -i ./flambert_main.mp4_1920x1080.I420 -W 1920 -H 1080 --intraperiod 300 \
--rcmode CBR -b 2000 -o ./flambert_kfdist300_2Mbps_ytranscode.vp9

yamitranscode -i ./flambert_main.mp4_1920x1080.I420 -W 1920 -H 1080 --intraperiod 300 \
--rcmode CBR -b 2000 -o -c VP9 ./flambert_kfdist300_2Mbps_ytranscode.ivf

fixes #31 

Signed-off-by: Daniel Charles <daniel.charles@intel.com>

### CODE REVIEW

File: tests/vppoutputencode.cpp [hunk 1]
```diff
@@ -52,18 +52,19 @@ TranscodeParams::TranscodeParams()
...
         if (!guessResolution(outputFileName, width, height))
             return false;
 
     m_fourcc = VA_FOURCC('N', 'V', '1', '2');
     m_width = width;
     m_height = height;
-    m_output.reset(EncodeOutput::create(outputFileName, m_width, m_height));
+    m_output.reset(EncodeOutput::create(outputFileName, m_width, m_height, codecName));
     return bool(m_output);
+    return m_output;
```
Comment (chivakker) [inline tests/vppoutputencode.cpp]: this second return has to be removed
